/*
 * generated by Xtext 2.35.0
 */
package tuber.xtext.validation;

import org.eclipse.xtext.validation.Check;

import tuber.Agent;
import tuber.City;
import tuber.Driver;
import tuber.Location;
import tuber.Ride;
import tuber.RideStatus;
import tuber.Rider;
import tuber.TuberPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class TSMLValidator extends AbstractTSMLValidator {
	
	@Check
	public void validate_capitalizedAgentName(Agent agent) {
		// TODO: Implement rule 1
	}
	
	@Check
	public void validate_LocationCoordinates(Location location) {
		// TODO: Implement rule 2
	}
	
	@Check
	public void checkStatus(Ride ride) {
		// TODO: Implement rule 3
    }
	
}
