/*
 * generated by Xtext 2.35.0
 */
package tuber.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTSMLScopeProvider extends DelegatingScopeProvider {
}
