/*
 * generated by Xtext 2.35.0
 */
package tuber.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TSMLUiModule extends AbstractTSMLUiModule {

	public TSMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
