/*
 * generated by Xtext 2.35.0
 */
package tuber.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import tuber.xtext.TSMLRuntimeModule;
import tuber.xtext.TSMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TSMLIdeSetup extends TSMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TSMLRuntimeModule(), new TSMLIdeModule()));
	}
	
}
