/*
 * generated by Xtext 2.35.0
 */
package tuber.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TSMLStandaloneSetup extends TSMLStandaloneSetupGenerated {

	public static void doSetup() {
		new TSMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
